---
language: ruby
rvm:
  - 2.4.4
bundler_args: --without system_tests
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpq-dev
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
