---
language: ruby
rvm:
  - 1.9.3
bundler_args: --without system_tests
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
